Repository kokonior/Javascript-Projects, pull requests merged in 2021-10, with the labels that each got.

#1 Create ristime.js
  ristime.js
Labels: good first issue, hacktoberfest-accepted

#2 Update ristime.js
  ristime.js
Labels: hacktoberfest-accepted

#3 Update ristime.js
  ristime.js
Labels: hacktoberfest-accepted

#4 Update ristime.js
  ristime.js
Labels: hacktoberfest-accepted

#5 Update ristime.js
  ristime.js
Labels: good first issue, hacktoberfest-accepted

#6 agunglaksonop#1
  agunglaksonop-PersegiPanjang.java
Labels: hacktoberfest-accepted

#7 agunglaksonop #2
  agunglaksonop-Persegi.java
Labels: hacktoberfest-accepted

#9 Update README.md
  README.md
Labels: hacktoberfest-accepted

#8 agunglaksonop #3
  agunglaksonop-lingkaran.java
Labels: hacktoberfest-accepted

#10 Create Sandi L. Putra
  Sandi L. Putra
Labels: good first issue, hacktoberfest-accepted

#12 Create index.js
  yusril/index.js
  yusril/package.json
Labels: Create

#13 Xirfk12.php
  ristime.js
Labels: hacktoberfest-accepted

#11 SGB: Created akbarhabiby.js and fizzBuzz function
  akbarhabiby.js
Labels: hacktoberfest-accepted

#14 rifki-persegi.java
  agunglaksonop-PersegiPanjang.java
Labels: hacktoberfest-accepted

#15 SGB: Created reverseText function with default args "Hello World"
  akbarhabiby.js
Labels: enhancement, hacktoberfest-accepted

#16 Create README.md
  yusril/README.md
Labels: hacktoberfest-accepted, Create

#17 SGB: Created vocalSeeker function and board constant
  akbarhabiby.js
Labels: good first issue, hacktoberfest-accepted

#22 Create zulnurdiana.js
  zulnurdiana.js
Labels: hacktoberfest-accepted

#21 Update agunglaksonop-Persegi.java
  agunglaksonop-Persegi.java
Labels: hacktoberfest-accepted

#20 Added Eilaluth.js [ Menghitung jumlah huruf dalam paragraf ]
  Eilaluth.js
Labels: hacktoberfest-accepted

#19 SGB: Created deepSum function and fixed log
  akbarhabiby.js
Labels: hacktoberfest-accepted

#18 Create efanwahyu
  efanwahyu
Labels: hacktoberfest-accepted, Create

#24 Create yaelahden.js
  yaelahden.js
Labels: hacktoberfest-accepted, Create

#23 Update zulnurdiana.js
  zulnurdiana.js
Labels: enhancement, hacktoberfest-accepted

#27 my thing
  pieckenst.js
Labels: good first issue, hacktoberfest-accepted

#26 Create yaelahdenxx0.js
  yaelahdenxx0.js
Labels: hacktoberfest-accepted, Create

#31 Create calculator.js
  calculator.js
Labels: hacktoberfest-accepted, Create

#30 Create README.md
  ilwan/README.md
Labels: hacktoberfest-accepted, Create

#29 Create bimaexz.js
  bimaexz.js
Labels: hacktoberfest-accepted, Create

#34 add bubble sort in js
  fatik07.js
Labels: good first issue, hacktoberfest-accepted

#33 Create covid-19.js
  ilwan/covid-19.js
Labels: hacktoberfest-accepted, Create

#32 Create guess_number.js
  guess_number.js
Labels: hacktoberfest-accepted, Create

#36 create htmlFragmentBersarang.js
  HtmlFragmentBersarang.js
Labels: hacktoberfest-accepted, Create

#37 Create package.json
  ilwan/package.json
Labels: hacktoberfest-accepted, Create

#40 Create currency-indonesia.js
  currency-indonesia.js
Labels: hacktoberfest-accepted, Create

#39 Update covid-19.js
  ilwan/covid-19.js
Labels: enhancement, hacktoberfest-accepted

#38 [hasbi] add array to object function
  hasbi-array-to-object.js
Labels: enhancement, hacktoberfest-accepted

#44 Create yaelahros.java
  yaelahros.java
Labels: hacktoberfest-accepted, Create

#43 Create demofarrel.js
  demofarrel.js
Labels: hacktoberfest-accepted, Create

#42 add project
  hide-unhide/3/index.php
  hide-unhide/3/style.css
  hide-unhide/3/tugas.html
Labels: hacktoberfest-accepted

#41 Create calculate_aris.js
  calculate_aris.js
Labels: hacktoberfest-accepted, Create

#48 Create BubbleSort.js
  BubbleSort.js
Labels: hacktoberfest-accepted, Create

#47 Adding triangle printers
  rzidinc.js
Labels: enhancement, hacktoberfest-accepted

#45 Update demofarrel.js
  demofarrel.js
Labels: enhancement, hacktoberfest-accepted

#50 Sleep Monitoring Algorithm
  SleepMonitoring.m
Labels: enhancement, hacktoberfest-accepted

#49 Create russss.js
  russss.js
Labels: hacktoberfest-accepted, Create

#51 Create garlek123.js
  garlek123.js
Labels: hacktoberfest-accepted, Create

#54 Add Quadratic Equation Function
  tajul.js
Labels: enhancement, hacktoberfest-accepted

#52 add project ahmadk-validation-file
  ahmadkfilevalidation.js
Labels: enhancement, hacktoberfest-accepted

#55 Added Additive Cipher code
  additive.js
Labels: good first issue, hacktoberfest-accepted

#56 Add file hurufVokal.js
  hurufVokal.js
Labels: enhancement, hacktoberfest-accepted

#57 menentukan bobot nilai dari grade nilai A,B,C,D,E
  grade.js
Labels: good first issue, hacktoberfest-accepted

#58 ayya4.js
  ayya4.js
Labels: enhancement, hacktoberfest-accepted

#60 bigbot
  new_big.js
Labels: hacktoberfest-accepted

#59 konvert suhu
  konvert-suhu_adrnsyh.js
Labels: hacktoberfest-accepted

#61 Create easyMath.js
  easyMath.js
Labels: hacktoberfest-accepted, Create

#63 Create recursive-function
  recursive-function
Labels: hacktoberfest-accepted, Create

#62 Create PopCatClicker.js
  PopCatClicker.js
Labels: hacktoberfest-accepted, Create

#64 creating fizzbuzz
  fizzbuzz.js
Labels: hacktoberfest-accepted

#67 Create nomorurut.js
  nomorurut.js
Labels: hacktoberfest-accepted, Create

#66 Create DMuhammad
  DMuhammad
Labels: hacktoberfest-accepted, Create

#279 Create Anjelica Webb.js
  Anjelica Webb.js
Labels: hacktoberfest-accepted

#280 Update Anjelica Webb.js
  Anjelica Webb.js
Labels: hacktoberfest-accepted

#282 Update Anjelica Webb.js
  Anjelica Webb.js
Labels: hacktoberfest-accepted

#283 Update Anjelica Webb.js
  Anjelica Webb.js
Labels: hacktoberfest-accepted

#284 Create Chip Abbey.js
  Chip Abbey.js
Labels: hacktoberfest-accepted

#285 Update Chip Abbey.js
  Chip Abbey.js
Labels: hacktoberfest-accepted

#286 Update Chip Abbey.js
  Chip Abbey.js
Labels: hacktoberfest-accepted

#287 Update Chip Abbey.js
  Chip Abbey.js
Labels: hacktoberfest-accepted

#288 Create spoilfew.js
  spoilfew.js
Labels: hacktoberfest-accepted

#289 Update spoilfew.js
  spoilfew.js
Labels: hacktoberfest-accepted

#290 Update spoilfew.js
  spoilfew.js
Labels: hacktoberfest-accepted

#291 Update spoilfew.js
  spoilfew.js
Labels: hacktoberfest-accepted

#292 Create Heather Hyland.js
  Heather Hyland.js
Labels: hacktoberfest-accepted

#293 Update Heather Hyland.js
  Heather Hyland.js
Labels: hacktoberfest-accepted

#294 Update Heather Hyland.js
  Heather Hyland.js
Labels: hacktoberfest-accepted

#295 Update Heather Hyland.js
  Heather Hyland.js
Labels: hacktoberfest-accepted

#296 Create Titus Burnham.js
  Titus Burnham.js
Labels: hacktoberfest-accepted

#297 Update Titus Burnham.js
  Titus Burnham.js
Labels: hacktoberfest-accepted

#298 Update Titus Burnham.js
  Titus Burnham.js
Labels: hacktoberfest-accepted

#299 Update Titus Burnham.js
  Titus Burnham.js
Labels: hacktoberfest-accepted

#300 Create Katharyn Nicolson.js
  Katharyn Nicolson.js
Labels: hacktoberfest-accepted

#301 Update Katharyn Nicolson.js
  Katharyn Nicolson.js
Labels: hacktoberfest-accepted

#302 Update Katharyn Nicolson.js
  Katharyn Nicolson.js
Labels: hacktoberfest-accepted

#303 Update Katharyn Nicolson.js
  Katharyn Nicolson.js
Labels: hacktoberfest-accepted

#306 Create GaeColton.js
  GaeColton.js
Labels: hacktoberfest-accepted

#307 Update GaeColton.js
  GaeColton.js
Labels: hacktoberfest-accepted

#308 Update GaeColton.js
  GaeColton.js
Labels: hacktoberfest-accepted

#309 Update GaeColton.js
  GaeColton.js
Labels: hacktoberfest-accepted

#310 Update GaeColton.js
  GaeColton.js
Labels: hacktoberfest-accepted

#311 Create Rube Martin.js
  Rube Martin.js
Labels: hacktoberfest-accepted

#312 Update Rube Martin.js
  Rube Martin.js
Labels: hacktoberfest-accepted

#314 Update Rube Martin.js
  Rube Martin.js
Labels: hacktoberfest-accepted

#313 Update Rube Martin.js
  Rube Martin.js
Labels: hacktoberfest-accepted

#315 Update README.md
  README.md
Labels: hacktoberfest-accepted

#316 Create thellongthenon.js
  thellongthenon.js
Labels: hacktoberfest-accepted

#317 Update thellongthenon.js
  thellongthenon.js
Labels: hacktoberfest-accepted

#318 Update thellongthenon.js
  thellongthenon.js
Labels: hacktoberfest-accepted

#319 Update thellongthenon.js
  thellongthenon.js
Labels: hacktoberfest-accepted

#320 Create brynnwiley.js
  brynnwiley.js
Labels: hacktoberfest-accepted

#321 Update brynnwiley.js
  brynnwiley.js
Labels: hacktoberfest-accepted

#322 Update brynnwiley.js
  brynnwiley.js
Labels: hacktoberfest-accepted

#323 Update brynnwiley.js
  brynnwiley.js
Labels: hacktoberfest-accepted

#324 Create wirtonburke.js
  wirtonburke.js
Labels: hacktoberfest-accepted

#325 Update wirtonburke.js
  wirtonburke.js
Labels: hacktoberfest-accepted

#326 Update wirtonburke.js
  wirtonburke.js
Labels: hacktoberfest-accepted

#327 Update wirtonburke.js
  wirtonburke.js
Labels: hacktoberfest-accepted

#328 add readme details
  README.md
Labels: hacktoberfest-accepted

#329 Create jobymercar.js
  jobymercar.js
Labels: hacktoberfest-accepted

#330 Update jobymercar.js
  jobymercar.js
Labels: hacktoberfest-accepted

#331 Update jobymercar.js
  jobymercar.js
Labels: hacktoberfest-accepted

#332 Update jobymercar.js
  jobymercar.js
Labels: hacktoberfest-accepted

#333 Create nisskenya.js
  nisskenya.js
Labels: hacktoberfest-accepted

#334 Update nisskenya.js
  nisskenya.js
Labels: hacktoberfest-accepted

#335 Update nisskenya.js
  nisskenya.js
Labels: hacktoberfest-accepted

#336 Update nisskenya.js
  nisskenya.js
Labels: hacktoberfest-accepted

#337 Website bookmark app using javascript
  Website Bookmark/application-image.png
  Website Bookmark/css/style.css
  Website Bookmark/index.html
  Website Bookmark/js/app.js
Labels: hacktoberfest-accepted
